# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

# azure-pipelines.yml
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'Product api/**'

pool:
  name: agent1
  
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectPath: 'Product api'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 8.0'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build Product API'
  inputs:
    command: 'build'
    projects: '$(projectPath)/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

#- task: DotNetCoreCLI@2
#  displayName: 'Run tests'
#  inputs:
#    command: 'test'
#    projects: '$(projectPath)/**/*[Tt]ests/*.csproj'
#    arguments: '--configuration $(buildConfiguration)'
#  continueOnError: true

- task: DotNetCoreCLI@2
  displayName: 'Publish Product API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '"$(projectPath)/**/*.csproj"'
    arguments: '--configuration $(buildConfiguration) --output "$(Build.ArtifactStagingDirectory)"'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'ProductAPI'